#TODO: add this file to .rsync-filter once all the repos have this version
name: Java CI
on:
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
  pull_request:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
jobs:

  pre-build:
    strategy:
      matrix:
        java: ['8', '11', '17']
    uses: micronaut-projects/micronaut-project-template/.github/workflows/reusable/gradle-pre-build.yml@master
    secrets: inherit
    with:
      java: ${{ matrix.java }}

#  ./gradlew check --no-daemon --parallel --continue

  build:
    needs: "pre-build (${{ matrix.java }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11', '17']
    uses: micronaut-projects/micronaut-project-template/.github/workflows/reusable/gradle-build.yml@master
    secrets: inherit
    with:
      build_command: |
#        Add additional variables as needed, for example:
#        export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
#        export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
#        export AWS_REGION="${{ secrets.AWS_REGION }}"
        ./gradlew check --no-daemon --parallel --continue

  post-build:
    needs: "build (${{ matrix.java }})"
    uses: micronaut-projects/micronaut-project-template/.github/workflows/reusable/gradle-post-build.yml@master
    secrets: inherit
    with:
      java: ${{ matrix.java }}
