name: Java CI
on:
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
  pull_request:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
jobs:

  pre-build:
    strategy:
      matrix:
        java: ['8', '11', '17']
    uses: micronaut-projects/micronaut-project-template/.github/workflows/reusable/gradle-pre-build.yml@master
    secrets: inherit
    with:
      java: ${{ matrix.java }}

#  ./gradlew check --no-daemon --parallel --continue

  build:
    needs: "pre-build (${{ matrix.java }})"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11', '17']
    uses: micronaut-projects/micronaut-project-template/.github/workflows/reusable/gradle-build.yml@master
    secrets: inherit
    with:
      build_command: "./gradlew check --no-daemon --parallel --continue"

  post-build:
    needs: "build (${{ matrix.java }})"
    uses: micronaut-projects/micronaut-project-template/.github/workflows/reusable/gradle-post-build.yml@master
    secrets: inherit
    with:
      java: ${{ matrix.java }}
