#TODO (in template-project): add this file to .rsync-filter once all the repos have this version
#TODO (in a concrete module): remove comments when accepting this change
name: Java CI
on:
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
  pull_request:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
jobs:

  pre-build:
    strategy:
      matrix:
        java: ['8', '11', '17']
    if: github.repository != 'micronaut-projects/micronaut-project-template'
    uses: micronaut-projects/micronaut-project-template/.github/workflows/reusable/gradle-pre-build.yml@master
    with:
      java: ${{ matrix.java }}
    secrets: inherit

#  ./gradlew check --no-daemon --parallel --continue

  build:
    strategy:
      matrix:
        java: ['8', '11', '17']
    needs: "pre-build (${{ matrix.java }})"
    if: github.repository != 'micronaut-projects/micronaut-project-template'
    uses: micronaut-projects/micronaut-project-template/.github/workflows/reusable/gradle-build.yml@master
    with:
      build_command: |
#        Add additional variables as needed, for example:
#        export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
#        export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
#        export AWS_REGION="${{ secrets.AWS_REGION }}"
        ./gradlew check --no-daemon --parallel --continue
    secrets: inherit

  post-build:
    if: github.repository != 'micronaut-projects/micronaut-project-template'
    needs: "build (${{ matrix.java }})"
    uses: micronaut-projects/micronaut-project-template/.github/workflows/reusable/gradle-post-build.yml@master
    with:
      java: ${{ matrix.java }}
    secrets: inherit
