#TODO: add this file to .rsync-filter once all the repos have this version
name: Static Analysis
on:
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
  pull_request:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
jobs:

  pre-build:
    uses: micronaut-projects/micronaut-project-template/.github/workflows/reusable/gradle-pre-build.yml@master
    secrets: inherit
    with:
      java: 11

  build:
    needs: pre-build
    uses: micronaut-projects/micronaut-project-template/.github/workflows/reusable/sonarqube-build.yml@master
    secrets: inherit
    with:
      build_command: |
#        Add additional variables as needed, for example:
#        export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
#        export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
#        export AWS_REGION="${{ secrets.AWS_REGION }}"
        ./gradlew check sonarqube --no-daemon --parallel --continue
